### ISSUE TITLE
Specify path to values file when installing a helm chart

### ISSUE THREAD

**Issue by leotsem** [CircleCI-Public/aws-eks-orb#23]
## What would you like to be added
Ability to pass a values file to `install-helm-chart`, similar to how `helm install -f` works. That allows environment-specific values files like `values.production.yaml` to be installed using this orb.

## Why is this needed
We're currently able to override specific values using `values-to-override`, which works if you only want to override just a few values but doesn't scale well if you have separate values files for reach environment.

**Comment by bobbywatson3** [comment]
This is a huge limitation. Configuring charts with values files is a fundamental requirement for deploying helm releases to multiple environments. Setting individual values is not a good enough work around.

**Comment by brivu** [comment]
We have removed jobs to install Helm in this orb and created a separate [Helm Orb here](https://circleci.com/developer/orbs/orb/circleci/helm).
