### ISSUE TITLE
ENV VARs are not being read

### ISSUE THREAD

**Issue by ianhundere** [CircleCI-Public/aws-eks-orb#31]
### Orb version

`1.0.0`

### What happened

After updating to `1.0.0` env vars are no longer getting picked up, so we get the following response when trying to authenticate:

```
#!/bin/bash -eo pipefail
CLUSTER_NAME="${EKS_CLUSTER_NAME}"
AWS_REGION=""
AWS_PROFILE=""
KUBECONFIG_FILE_PATH=""
ROLE_ARN=""
CLUSTER_CONTEXT_ALIAS=""
DRY_RUN="false"
VERBOSE="false"
if [ -n "${CLUSTER_NAME}" ]; then
  set -- "$@" --name "${CLUSTER_NAME}"
fi
if [ -n "${AWS_REGION}" ]; then
  set -- "$@" --region "${AWS_REGION}"
fi
if [ -n "${AWS_PROFILE}" ]; then
  set -- "$@" --profile "${AWS_PROFILE}"
fi
if [ -n "${KUBECONFIG_FILE_PATH}" ]; then
  set -- "$@" --kubeconfig "${KUBECONFIG_FILE_PATH}"
fi
if [ -n "${ROLE_ARN}" ]; then
  set -- "$@" --role-arn "${ROLE_ARN}"
fi
if [ -n "${CLUSTER_CONTEXT_ALIAS}" ]; then
  set -- "$@" --alias "${CLUSTER_CONTEXT_ALIAS}"
fi
if [ "${DRY_RUN}" == "true" ]; then
  set -- "$@" --dry-run
fi
if [ "${VERBOSE}" == "true" ]; then
  set -- "$@" --verbose
fi
aws eks update-kubeconfig "$@"

Invalid endpoint: https://eks..amazonaws.com

Exited with code exit status 255
CircleCI received exit code 255
```
### Expected behavior

env vars should be recognized

### Example of `.circleci.yml`

```  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Load the environment variables in to bash env
          command: source ./setup-env.sh
      - run:
          name: Load Build Image for Deployment
          command: docker load -i Dockerfile.tar
      - aws-ecr/ecr-login:
          region: AWS_DEFAULT_REGION
      - aws-ecr/push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          repo: app
          tag: "$CIRCLE_SHA1,latest"
      - kubernetes/install-kubectl
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: ${EKS_CLUSTER_NAME}
```

**Comment by lokst** [comment]
@ianhundere May I know which env vars in particular are not being read? Where are they being set?

**Comment by ianhundere** [comment]
we have a script that exports them to `{BASH_ENV}`; e.g. `echo 'export AWS_REGION="us-east-1"' >> $BASH_ENV`

none of these vars are working anymore with `1.0.0`

**Comment by lokst** [comment]
@ianhundere Thanks for the clarification. At least for `AWS_REGION` I believe the reason the value from your script is not present is because in the `update-kubeconfig-with-authenticator`  command there is an env var of the same name overriding it. This behavior, while not ideal, is present in older versions of the orb too.

**Comment by lokst** [comment]
I'll make a PR to use an alternative name for the env var, this should resolve the conflict.

**Comment by ianhundere** [comment]
it's working with `0.2.7` with no issue using the same `config.yml`

**Comment by lokst** [comment]
@ianhundere Looking at this issue again, I don't think there's a conflict with `AWS_REGION` after all, because it's supposed to takes its value from the command parameter. So it doesn't seem that changing this line https://github.com/CircleCI-Public/aws-eks-orb/blob/master/src/commands/update-kubeconfig-with-authenticator.yml#L78 will help with your issue. Would you be able to link me to a successful build with the earlier version of the orb, and a failed build with `1.0.0` to facilitate comparison of the differences?

**Comment by ianhundere** [comment]
@lokst sure, how should i share that with you?

also, it looks as if none of our env vars are reading, not just `AWS_REGION`.

**Comment by lokst** [comment]
> @lokst sure, how should i share that with you?
> 
> also, it looks as if none of our env vars are reading, not just `AWS_REGION`.

You can either link here to the builds, or open a support ticket here: https://support.circleci.com/hc/en-us/requests/new

Could you also mention the names of other env vars that are not reading, and also in which run step do you see that the values of those env vars were different from expected?

**Comment by ianhundere** [comment]
i don't believe any env vars are being read, but the main var that's needed is `EKS_CLUSTER_NAME` which is not being read.

i'll open a support ticket and link to this issue.

**Comment by ianhundere** [comment]
Opened a support ticket; #76729.

**Comment by lokst** [comment]
@ianhundere Thank you, I received the details from the support ticket. I suspect ${EKS_CLUSTER_NAME} is actually being read, and that it may be an issue with the region. Looking at the `Configure AWS default region` step, it is setting the default region based on `AWS_DEFAULT_REGION`, while you mentioned that the bash script sets `AWS_REGION`.

Could you try configuring the `aws-region` parameter like so:

```
- aws-eks/update-kubeconfig-with-authenticator:
     cluster-name: ${EKS_CLUSTER_NAME}
     aws-region: ${AWS_REGION}     
```

You could also add this step after `update-kubeconfig-with-authenticator` to check what the values are
```
- run:
     command: echo "EKS_CLUSTER_NAME is ${EKS_CLUSTER_NAME} and AWS_REGION is ${AWS_REGION} and AWS_DEFAULT_REGION is ${AWS_DEFAULT_REGION}"
     when: on_fail
```

**Comment by ianhundere** [comment]
ah, that totally fixed it.

`aws-region: ${AWS_REGION}`

the docs need to be updated:
https://circleci.com/orbs/registry/orb/circleci/aws-eks#commands-update-kubeconfig-with-authenticator

thanks so much for your help / quick response time.

cheers,
thank you!

**Comment by lokst** [comment]
@ianhundere Thank you for your patience in troubleshooting this with us too!

**Comment by andreimarinescu** [comment]
Hey guys. Just a heads up that the docs haven't seem to have been updated and the tutorial still doesn't also use `aws-region`, causing just a bit of confusion when trying to deploy a new pipeline.

https://circleci.com/developer/orbs/orb/circleci/aws-eks#commands-update-kubeconfig-with-authenticator (aws region not required)

https://circleci.com/developer/orbs/orb/circleci/aws-eks (test cluster job definition not passing aws-region as a parameter)

**Comment by kingjerod** [comment]
Still an issue, should use the AWS_REGION from env variables by default.
