### ISSUE TITLE
aws-eks -ctl installation is failing due to incorrect URL.

### ISSUE THREAD

**Issue by pdhanoyasplunk** [CircleCI-Public/aws-eks-orb#42]
### Orb version
1.1.0

### What happened
Installation Failed due to incorrect  URL 
"https://github.com/weaveworks/eksctl/releases/download/latest_release/eksctl_$(uname -s)_amd64.tar.gz"

### Expected behavior
eks-ctl install should work as expected 
![image](https://user-images.githubusercontent.com/69360493/131193011-f603ced6-cdb6-4ed0-8be3-8a373c64c97b.png)

**Comment by superafroman** [comment]
FYI, correct URL is for example `https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_Linux_amd64.tar.gz`. i.e. `https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz`

**Comment by tenhishadow** [comment]
why don't just do eksctl installation optional? Cause sometimes you don't need it really and it's great to disable it. It's wasting budget if it's not needed

**Comment by raghav20** [comment]
this is blocking our deployment pipeline

**Comment by raghav20** [comment]
@superafroman  is it fixed ?

**Comment by superafroman** [comment]
@raghav20 it's fixed in my PR. While you wait for it to be approved and a new release done, you can replace the following line in your circleci config 
```
      - aws-eks/install-eksctl
```

with 

```

  - run:
      name: Install the eksctl tool
      command: |
        if which eksctl > /dev/null; then
          echo "eksctl is already installed"
          exit 0
        fi
        mkdir -p eksctl_download
        curl --silent --location --retry 5 "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" \
          | tar xz -C eksctl_download
        chmod +x eksctl_download/eksctl
        SUDO=""
        if [ $(id -u) -ne 0 ] && which sudo > /dev/null ; then
          SUDO="sudo"
        fi
        $SUDO mv eksctl_download/eksctl /usr/local/bin/
        rmdir eksctl_download
```

**Comment by raghav20** [comment]
hello @superafroman thankyou for your rresponse, we dont use this orb but its called internaly by aws/create-cluster

**Comment by fmmricardo** [comment]
Hello @superafroman  and @raghav20 , any updates here? I'm also blocked. And I'm on the same situation that @raghav20 is. I'm using it internally when calling aws-eks/create-cluster.

**Comment by raghav20** [comment]
Hello Ricardo ,
Based on superafroman suggestion we got it working with create-cluster too
something like this in


Sample code :
setup-cluster-with-params:
parameters:
executor:
type: executor
cluster-name:
type: string
region:
type: string
default: ""
zones:
type: string
default: ""
executor: << parameters.executor >>
steps:
- run:
name: Install the eksctl tool
command: |
if which eksctl > /dev/null; then
echo "eksctl is already installed"
exit 0
fi
mkdir -p eksctl_download
curl --silent --location --retry 5 "
https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname
-s)_amd64.tar.gz" \
| tar xz -C eksctl_download
chmod +x eksctl_download/eksctl
SUDO=""
if [ $(id -u) -ne 0 ] && which sudo > /dev/null ; then
SUDO="sudo"
fi
$SUDO mv eksctl_download/eksctl /usr/local/bin/
rmdir eksctl_download
- aws-eks/create-cluster:
cluster-name: << parameters.cluster-name >>
node-type: "t2.small"
aws-region: << parameters.region >>
nodes: 1
nodes-min: 1
nodes-max: 2

**Comment by fmmricardo** [comment]
Thanks for the help @raghav20, I will try it. 👌

**Comment by SudKul** [comment]
Duplicates https://github.com/CircleCI-Public/aws-eks-orb/issues/47
