### ISSUE TITLE
AWS Iam auhenticator installation is broken

### ISSUE THREAD

**Issue by antweiss** [CircleCI-Public/aws-eks-orb#59]
### What happened

Getting:
`curl: (3) URL using bad/illegal format or missing URL`

Reason:
```
DOWNLOAD_URL=$(curl -s --retry 5 "${RELEASE_URL}" \
    | grep "${PLATFORM}" | awk '/browser_download_url/ {print $2}' | sed 's/"//g')
echo $DOWNLOAD_URL
https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/download/v0.5.5/aws-iam-authenticator_0.5.5_linux_amd64
https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/download/v0.5.5/aws-iam-authenticator_0.5.5_linux_arm64

^ this now returns 2 urls instead of one, which breaks curl

### Expected behavior

<!--- what should happen, ideally? -->

**Comment by parkerjm** [comment]
yep, our deployment is broken here.... any work arounds?

**Comment by antweiss** [comment]
Well, I fixed it by locking the release version to one before latest.
`authenticator-release-tag: v0.5.3`
But ideally need to add grep for amd64.

**Comment by antweiss** [comment]
Looking at the code - this was probably already fixed, I'm on an old version of the orb.

**Comment by parkerjm** [comment]
ah yeah got it, I was also on a super old version. upgrading to latest fixed it.
