### ISSUE TITLE
install-aws-iam-authenticator command fails on newest aws-iam-authenticator release

### ISSUE THREAD

**Issue by versus** [CircleCI-Public/aws-eks-orb#62]
### Orb version

2.1.1

### What happened

The install-aws-iam-authenticator command is failing our builds because the aws-iam-authenticator project pushed a release that does not contain binary assets.

'''
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 

Exited with code exit status 22
CircleCI received exit code 22
'''

### Expected behavior

Revert to a known good build. It would be ideal if the release version of the aws-iam-authenticator could be check 404 error when we download aws-iam-authenticator and downgrade version

**Comment by milosivanovic** [comment]
Supposedly the following should fix it (by locking to the previous release), but it doesn't appear to work for me, and still tries to download the latest:

```
- aws-eks/update-kubeconfig-with-authenticator:
     authenticator-release-tag: v0.5.6
```

**Comment by emrebozkurtemonvia** [comment]
> Supposedly the following should fix it (by locking to the previous release), but it doesn't appear to work for me, and still tries to download the latest:
> 
> ```
> - aws-eks/update-kubeconfig-with-authenticator:
>     authenticator-release-tag: v0.5.6
> ```

try this maybe: `authenticator-release-tag: "v0.5.6"`

**Comment by versus** [comment]
I added  check for latest version of authenticator with binary release
https://github.com/CircleCI-Public/aws-eks-orb/pull/63

**Comment by russellraed** [comment]
> > Supposedly the following should fix it (by locking to the previous release), but it doesn't appear to work for me, and still tries to download the latest:
> > ```
> > - aws-eks/update-kubeconfig-with-authenticator:
> >     authenticator-release-tag: v0.5.6
> > ```
> 
> try this maybe: `authenticator-release-tag: "v0.5.6"` it worked for us like that

Unfortunately this does not work for us.

**Comment by jacobleesinger** [comment]
I'm getting `/bin/bash: line 13: v0.5.6: invalid variable name` when using `authenticator-release-tag: v0.5.6`, both with and without the quotes. (using orb version 2.1.1)

**Comment by russellraed** [comment]
Work-around for the meantime, add this:
```
      - run:
          command: |
            curl -o aws-iam-authenticator https://s3.us-west-2.amazonaws.com/amazon-eks/1.21.2/2021-07-05/bin/linux/amd64/aws-iam-authenticator
            chmod +x ./aws-iam-authenticator
            mkdir -p $HOME/bin && cp ./aws-iam-authenticator $HOME/bin/aws-iam-authenticator && export PATH=$PATH:$HOME/bin
            echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
            aws-iam-authenticator help
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
            kubectl version --client
```

**Comment by dersnek** [comment]
`authenticator-release-tag: v0.5.6` works if you you downgrade your orb version to 1.2.0, `aws-eks: circleci/aws-eks@1.2.0`

**Comment by jazzywhit** [comment]
I have another work around, although I still think that the original bash script should be fixed...

Add an environment varible to your Circle CI project called `AWS_AUTHENTICATOR_VARIABLE` (or whatever you want) that resolves to the target version. In my case I needed to use 0.6.11 because 0.6.12 is missing binaries.

In your Workflow jobs set `authenticator-release-tag: "AWS_AUTHENTICATOR_VARIABLE"` like so:

```
      - aws-eks/update-container-image:
          name: name
          authenticator-release-tag: "AWS_AUTHENTICATOR_VARIABLE"
```

Then in your jobs where you are defining your Docker image do something like this:

```
  run_command:
    docker:
      - image: "cimg/python:3.11.4"
        environment:
          AWS_AUTHENTICATOR_VARIABLE: $AWS_AUTHENTICATOR_VARIABLE
```

This will ensure that you can set the variable on the project, and then you can properly get around the indirect reference in the bash script.

**Comment by stoiev** [comment]
Maybe orb could freeze this binary in lastest version in every release? In CIs, it seems preferable to choose stability over other trade offs.

**Comment by jazzywhit** [comment]
Just found out that `aws-eks: circleci/aws-eks@2.2.0` will work now, as they removed the indirect reference in the bash script. So now if you use that version you just need to set the tag version without jumping through hoops!

```
      - aws-eks/update-container-image:
          name: name
          authenticator-release-tag: "0.6.11"
````
