### ISSUE TITLE
Orb should respect env vars for AWS values

### ISSUE THREAD

**Issue by eddiewebb** [CircleCI-Public/aws-eks-orb#9]
Orb requires common variables like region to be passed as parameter, with an empty default overriding environmant values.

Default should be `${AWS_REGION}`

**Comment by dsayling** [comment]
Hey @lokst, @KyleTryon and I have been looking over this request and the closed PR above and have a few questions and concerns with this.

With the way the `eksctl` works, not providing flags to the cluster create command (which occurs when leaving the default parameters as they are) causes `eksctl` to provide its own default values. We believe the parameter, `aws-region` was intentionally left blank so the region in the config file would be used.  

This is the help doesn't say what the default would be, but were assume it comes from the config
```
/ # eksctl create cluster --help
Create a cluster

Usage: eksctl create cluster [flags]

General flags:
  -n, --name string           EKS cluster name (generated if unspecified, e.g. "ferocious-gopher-1613153548")
      --tags stringToString   A list of KV pairs used to tag the AWS resources (e.g. "Owner=John Doe,Team=Some Team") (default [])
  -r, --region string         AWS region
      --zones strings         (auto-select if unspecified)
      --version string        Kubernetes version (valid options: 1.10, 1.11) (default "1.11")
  -f, --config-file string    load configuration from a file

Initial nodegroup flags:
      --nodegroup-name string          name of the nodegroup (generated if unspecified, e.g. "ng-31e01c67")
      --without-nodegroup              if set, initial nodegroup will not be created
  -t, --node-type string               node instance type (default "m5.large")
  -N, --nodes int                      total number of nodes (for a static ASG) (default 2)
  -m, --nodes-min int                  minimum nodes in ASG (default 2)
  -M, --nodes-max int                  maximum nodes in ASG (default 2)
      --node-volume-size int           node volume size in GB
      --node-volume-type string        node volume type (valid options: gp2, io1, sc1, st1) (default "gp2")
      --max-pods-per-node int          maximum number of pods per node (set automatically if unspecified)
      --ssh-access                     control SSH access for nodes
      --ssh-public-key string          SSH public key to use for nodes (import from local path, or use existing EC2 key pair) (default "~/.ssh/id_rsa.pub")
```

Another thing, if the user had `$AWS_REGION` set and they did not set `aws-region` param in the command usage, we would override the envvar with an empty string when the step runs. This may be causing the issue at hand. So if your config file is set, you would be fine, but if you're relying on the env var you might be out of luck.

We're going to open up a new issue to address the concerns around overriding the variables and updating the CI pipeline to the latest orb tools version

**Comment by gmemstr** [comment]
A larger rework of this orb is probably required -- going to open a new issue for this as Drew mentioned.
